### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [xXPancakeXx/Win10-Explorer#17]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by ste-phil** [comment]
Hey,

the project has been on hold for a while now because of a couple things, but here are the most two of them.

1. my lack of time 😅
2. microsoft lack of commitment for uwp as well as the overall bad performance that comes with with it. 

Besides that, if you still wish to help out this project I can add you to the list of contributors.

Greetings.

**Comment by ghost** [comment]
Hi ste-phil.

> Hey,
> the project has been on hold for a while now because of a couple things, but here are the most two of them.
> my lack of time sweat_smile
microsoft lack of commitment for uwp as well as the overall bad performance that comes with with it.
Besides that, if you still wish to help out this project I can add you to the list of contributors.
> Greetings.

thank you for feedback.
